### ISSUE TITLE
Tracking issue for TypeScript documentation

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1343]
- [x] [src/channel.d.ts](https://github.com/observablehq/plot/blob/main/src/channel.d.ts)
- [x] ~~[src/color.d.ts](https://github.com/observablehq/plot/blob/main/src/color.d.ts)~~
- [x] [src/context.d.ts](https://github.com/observablehq/plot/blob/main/src/context.d.ts)
- [x] [src/curve.d.ts](https://github.com/observablehq/plot/blob/main/src/curve.d.ts)
- [x] [src/dimensions.d.ts](https://github.com/observablehq/plot/blob/main/src/dimensions.d.ts)
- [x] ~~[src/facet.d.ts](https://github.com/observablehq/plot/blob/main/src/facet.d.ts)~~
- [x] [src/format.d.ts](https://github.com/observablehq/plot/blob/main/src/format.d.ts)
- [x] [src/inset.d.ts](https://github.com/observablehq/plot/blob/main/src/inset.d.ts)
- [x] ~~[src/interpolate.d.ts](https://github.com/observablehq/plot/blob/main/src/interpolate.d.ts)~~
- [x] [src/interval.d.ts](https://github.com/observablehq/plot/blob/main/src/interval.d.ts)
- [x] [src/legends.d.ts](https://github.com/observablehq/plot/blob/main/src/legends.d.ts)
- [x] [src/mark.d.ts](https://github.com/observablehq/plot/blob/main/src/mark.d.ts) [#1405](https://github.com/observablehq/plot/pull/1405)
- [x] [src/marker.d.ts](https://github.com/observablehq/plot/blob/main/src/marker.d.ts)
- [x] [src/marks/area.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/area.d.ts) [#1402](https://github.com/observablehq/plot/pull/1402)
- [x] [src/marks/arrow.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/arrow.d.ts) [#1398](https://github.com/observablehq/plot/pull/1398)
- [x] [src/marks/auto.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/auto.d.ts) [#1385](https://github.com/observablehq/plot/pull/1385)
- [x] [src/marks/axis.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/axis.d.ts) [#1403](https://github.com/observablehq/plot/pull/1403)
- [x] [src/marks/bar.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/bar.d.ts) [#1397](https://github.com/observablehq/plot/pull/1397)
- [x] [src/marks/box.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/box.d.ts) [#1394](https://github.com/observablehq/plot/pull/1394)
- [x] [src/marks/cell.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/cell.d.ts) [#1396](https://github.com/observablehq/plot/pull/1396)
- [x] [src/marks/contour.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/contour.d.ts) [#1386](https://github.com/observablehq/plot/pull/1386)
- [x] [src/marks/delaunay.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/delaunay.d.ts) [#1393](https://github.com/observablehq/plot/pull/1393)
- [x] [src/marks/density.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/density.d.ts) [#1392](https://github.com/observablehq/plot/pull/1392)
- [x] [src/marks/dot.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/dot.d.ts) [#1370](https://github.com/observablehq/plot/pull/1370)
- [x] [src/marks/frame.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/frame.d.ts) [#1375](https://github.com/observablehq/plot/pull/1375)
- [x] [src/marks/geo.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/geo.d.ts) [#1391](https://github.com/observablehq/plot/pull/1391)
- [x] [src/marks/hexgrid.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/hexgrid.d.ts) [#1389](https://github.com/observablehq/plot/pull/1389)
- [x] [src/marks/image.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/image.d.ts) [#1395](https://github.com/observablehq/plot/pull/1395)
- [x] [src/marks/line.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/line.d.ts) [#1401](https://github.com/observablehq/plot/pull/1401)
- [x] [src/marks/linearRegression.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/linearRegression.d.ts) [#1390](https://github.com/observablehq/plot/pull/1390)
- [x] [src/marks/link.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/link.d.ts) [#1388](https://github.com/observablehq/plot/pull/1388)
- [x] [src/marks/raster.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/raster.d.ts) [#1386](https://github.com/observablehq/plot/pull/1386)
- [x] [src/marks/rect.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/rect.d.ts) [#1383](https://github.com/observablehq/plot/pull/1383)
- [x] [src/marks/rule.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/rule.d.ts) [#1379](https://github.com/observablehq/plot/pull/1379)
- [x] [src/marks/text.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/text.d.ts) [#1381](https://github.com/observablehq/plot/pull/1381)
- [x] [src/marks/tick.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/tick.d.ts) [#1378](https://github.com/observablehq/plot/pull/1378)
- [x] [src/marks/tree.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/tree.d.ts) [#1351](https://github.com/observablehq/plot/pull/1351)
- [x] [src/marks/vector.d.ts](https://github.com/observablehq/plot/blob/main/src/marks/vector.d.ts) [#1377](https://github.com/observablehq/plot/pull/1377)
- [x] [src/options.d.ts](https://github.com/observablehq/plot/blob/main/src/options.d.ts) [#1369](https://github.com/observablehq/plot/pull/1369)
- [x] [src/plot.d.ts](https://github.com/observablehq/plot/blob/main/src/plot.d.ts)
- [x] [src/projection.d.ts](https://github.com/observablehq/plot/blob/main/src/projection.d.ts) [#1374](https://github.com/observablehq/plot/pull/1374)
- [x] [src/reducer.d.ts](https://github.com/observablehq/plot/blob/main/src/reducer.d.ts) [#1360](https://github.com/observablehq/plot/pull/1360)
- [x] [src/scales.d.ts](https://github.com/observablehq/plot/blob/main/src/scales.d.ts) [#1371](https://github.com/observablehq/plot/pull/1371)
- [x] [src/symbol.d.ts](https://github.com/observablehq/plot/blob/main/src/symbol.d.ts)
- [x] [src/transforms/basic.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/basic.d.ts) [#1369](https://github.com/observablehq/plot/pull/1369)
- [x] [src/transforms/bin.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/bin.d.ts) [#1360](https://github.com/observablehq/plot/pull/1360)
- [x] [src/transforms/centroid.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/centroid.d.ts) [#1362](https://github.com/observablehq/plot/pull/1362)
- [x] [src/transforms/dodge.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/dodge.d.ts) [#1361](https://github.com/observablehq/plot/pull/1361)
- [x] [src/transforms/group.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/group.d.ts) [#1360](https://github.com/observablehq/plot/pull/1360)
- [x] [src/transforms/hexbin.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/hexbin.d.ts) [#1359](https://github.com/observablehq/plot/pull/1359)
- [x] [src/transforms/map.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/map.d.ts) [#1358](https://github.com/observablehq/plot/pull/1358)
- [x] [src/transforms/normalize.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/normalize.d.ts)  [#1354](https://github.com/observablehq/plot/pull/1354)
- [x] [src/transforms/select.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/select.d.ts)  [#1353](https://github.com/observablehq/plot/pull/1353)
- [x] [src/transforms/stack.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/stack.d.ts) [#1352](https://github.com/observablehq/plot/pull/1352)
- [x] [src/transforms/tree.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/tree.d.ts) [#1351](https://github.com/observablehq/plot/pull/1351)
- [x] [src/transforms/window.d.ts](https://github.com/observablehq/plot/blob/main/src/transforms/window.d.ts)  [#1349](https://github.com/observablehq/plot/pull/1349)
