### ISSUE TITLE
Tracking issue for new documentation

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1443]
Ref. #1435
- [x] [index.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/index.md)
- [x] [what-is-plot.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/what-is-plot.md)
- [x] [why-plot.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/why-plot.md)
- [x] [getting-started.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/getting-started.md)
- [x] [community.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/community.md)
- [x] [features/plots.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/plots.md)
- [x] [features/marks.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/marks.md)
- [x] [features/scales.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/scales.md)
- [x] [features/projections.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/projections.md)
- [x] [features/transforms.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/transforms.md)
- [x] [features/facets.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/facets.md)
- [x] [features/legends.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/legends.md)
- [x] [features/curves.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/curves.md)
- [x] [features/formats.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/formats.md)
- [x] [features/markers.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/markers.md)
- [x] [features/shorthand.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/shorthand.md)
- [x] [features/spatial-interpolators.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/spatial-interpolators.md)
- [x] [features/accessibility.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/features/accessibility.md)
- [x] [marks/area.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/area.md)
- [x] [marks/arrow.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/arrow.md)
- [x] [marks/auto.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/auto.md)
- [x] [marks/axis.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/axis.md)
- [x] [marks/bar.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/bar.md)
- [x] [marks/box.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/box.md)
- [x] [marks/cell.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/cell.md)
- [x] [marks/contour.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/contour.md)
- [x] [marks/delaunay.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/delaunay.md)
- [x] [marks/density.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/density.md)
- [x] [marks/dot.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/dot.md)
- [x] [marks/frame.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/frame.md)
- [x] [marks/geo.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/geo.md)
- [x] [marks/grid.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/grid.md)
- [x] [marks/hexgrid.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/hexgrid.md)
- [x] [marks/image.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/image.md)
- [x] [marks/line.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/line.md)
- [x] [marks/linear-regression.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/linear-regression.md)
- [x] [marks/link.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/link.md)
- [x] [marks/raster.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/raster.md)
- [x] [marks/rect.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/rect.md)
- [x] [marks/rule.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/rule.md)
- [x] [marks/text.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/text.md)
- [x] [marks/tick.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/tick.md)
- [x] [marks/tree.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/tree.md)
- [x] [marks/vector.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/marks/vector.md)
- [x] [transforms/bin.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/bin.md)
- [x] [transforms/centroid.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/centroid.md)
- [x] [transforms/dodge.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/dodge.md)
- [x] [transforms/filter.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/filter.md)
- [x] [transforms/group.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/group.md)
- [x] [transforms/hexbin.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/hexbin.md)
- [x] [transforms/interval.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/interval.md)
- [x] [transforms/map.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/map.md)
- [x] [transforms/normalize.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/normalize.md)
- [x] [transforms/select.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/select.md)
- [x] [transforms/sort.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/sort.md)
- [x] [transforms/stack.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/stack.md)
- [x] [transforms/tree.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/tree.md)
- [x] [transforms/window.md](https://github.com/observablehq/plot/blob/mbostock/vitepress/docs/transforms/window.md)
