### ISSUE TITLE
More warnings

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#755]
Continuing from #536…

- [ ] undefined or invalid data #493
- [ ] negative data on a positive log scale #534
- [ ] too many ordinal values #74
- [ ] cycling the ordinal color scale because we have more categories than colors
- [ ] infinite values #528
- [ ] on-the-fly data coercion #532
- [ ] insets that result in invisible rects
- [ ] insets and margins that result in scale range collapse

**Comment by kentr** [comment]
Suggestion: 

Warning for the cases where mark data is not parallel to facet data. I.e., cases that are warned about here:

> When the include or exclude facet mode is chosen, the mark data must be parallel to the facet data: the mark data must have the same length and order as the facet data. If the data are not parallel, then the wrong data may be shown in each facet. The default auto therefore requires strict equality (===) for safety, and using the facet data as mark data is recommended when using the exclude facet mode. (To construct parallel data safely, consider using [array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) on the facet data.)

**Comment by mkfreeman** [comment]
It would be great to surface a warning when someone uses `Plot.barY` with a continuous `x` (which results in over-labeling the ticks on the x axis). 

<img width="576" alt="Screen Shot 2022-03-16 at 2 39 50 PM" src="https://user-images.githubusercontent.com/1373882/158663398-bffc451c-251a-4200-a3eb-b627cfebd8aa.png">
.

Relatedly `Plot.barX` with a continuous `y`. Maybe even `Plot.groupX` with a continuous `x` and `Plot.groupY` with a continuous `y` (nudging them towards binning continuous values)?

**Comment by mbostock** [comment]
@mkfreeman Here’s an example to make the pattern you describe more explicit:

![untitled (20)](https://user-images.githubusercontent.com/230541/158679684-164e8fe6-4e30-4c8c-a090-5524fa6278cf.png)

```js
Plot.barY([[1, 1], [2, 2], [3, 3]], {x: "0", y: "1"}).plot()
```

The warning would be triggered by `values.some(isNumeric)` here:

https://github.com/observablehq/plot/blob/66142e2c096439cffea0ed390de13c6cf1545388/src/scales.js#L150-L152

I recall considering this warning earlier, and I think I didn’t do it because the default _x_ channel for Plot.barY is `indexOf` which is numeric. We wouldn’t want the [barY shorthand](https://observablehq.com/@observablehq/plot-shorthand) to generate a warning. That said, we could be more selective in our warning:

* If the channel is numeric and there are any gaps between numbers? Though this would require detecting when the numbers are integers, and presumably would want to support both ascending and descending sequences. Alternatively we could just special-case 0, 1, 2, 3, … but that seems like cheating.
* If the channel is numeric and there are more than TK distinct values (high cardinality)?
* Or more generally if there are more than TK distinct values?

Related #74 which is also about high-cardinality ordinal domains. Though that’s not the only problem here—the other reason we want to warn about numeric data being treated as ordinal is that it makes it hard to see missing values (gaps in the data).

**Comment by mkfreeman** [comment]
Thanks for elaborating @mbostock -- agreed that we don't want the shorthand to generate a warning. I think _If the channel is numeric and there are any gaps between numbers?_ would still miss the common case of too many ticks being drawn (as you noted, #74). I'm not sure if there's a simple way to check if the shorthand is being used (e.g., if the channel was set explicitly or not), but perhaps we could provide a warning if the channel is numeric _and_  it was explicitly declared (using a string or function?).

**Comment by mbostock** [comment]
> perhaps we could provide a warning if the channel is numeric and it was explicitly declared

Generally speaking we try to do the opposite, which is to declare warnings in cases where the Plot specification is ambiguous (_underspecified_), such as when the scale type is not explicitly declared. This provides a consistent way to suppress warnings by stating more explicitly what you intend to happen (you always _add_ to a specification to suppress a warning, not remove). In other words I don’t think we should give the shorthand a special exemption around this error; if you specify `x: (d, i) => i` explicitly then I wouldn’t want a warning either.

**Comment by mkfreeman** [comment]
Just wanted to ➕ @kentr 's suggestion above and provide an example notebook: https://observablehq.com/d/a869f84e397d44b7

**Comment by Fil** [comment]
- [ ] using a log scale on marks that implicitly use a zero baseline (#1039)

**Comment by yurivish** [comment]
It would be nice if there were a warning attached to any plot that has a `Plot.geo` mark but has not specified a projection, instructing the user to specify `projection: null` to disable the warning. Right now making a plot with `Plot.geo(geojson).plot()` produces an empty plot.

I mentioned this on the d3js slack and @fil added some nuance:

> Note that you can use Plot.geo in conjunction with a dot mark (or any other mark that defines x and y scales); in that case the geo will be projected onto the x/y coordinate system. The warning would only be necessary if there is geo and no projection nor x/y scales.

**Comment by mwaibel-go** [comment]
I’m not sure if this is too deep in the realm of developer stupidity to warrant a warning, but this definition:

```js
Plot.plot({
  x: { interval: 1 },
  marks: [Plot.tickY(
    [new Date('2026-08-01'), new Date('2026-08-03')],
    {x: (d) => d}
  )]
})
```

can cause the  JavaScript engine to run out of memory. The interval is interpreted as 1 millisecond, which causes [d3-array](https://github.com/d3/d3-array/blob/be0ae0d2b36ab91b833294ad2cfc5d5905acbd0f/src/range.js#L1-L6) to produce an array of size 172,800,000.
