### ISSUE TITLE
layout issues

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#898]
- [x] Plot.dodge crashes on {r: {type:"identity"}}
- [x] If you plot `Plot.dot(olympians, Plot.dodgeX({ y: "sport"})).plot()` the browser hangs (note: it's only a performance issue: after a few minutes the chart has been generated) #901 is about 2x faster
- [x] Plot.text(dodge(…)) doesn't take the "r" channel (#899)
- [x] the transform could propagate the channel labels (#900)
- [x] The dodge transform should sort by descending radius by default?
- [x] <del>Plot.hexbin(Plot.dodgeY()) isn't always working</del> (not a bug; what confused me is that hexbin sets *r* and dodge too, but they don't have the same defaults. Setting *r* explicitly is the solution)
- [x] <del>The dodge _padding_ option is not documented in README</del> (EDIT: it was)
