### ISSUE TITLE
Follow-ups on Delaunay/Voronoi

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#928]
- [ ] In #917, the Voronoi mark uses the full frame. As a consequence, it doesn't work well with `clip: true` (since it is exactly on the clipping path). the way to fix it might be to add a _padding_ (or _inset_) option.
- [ ] Add a _curve_ option on the voronoi cells
- [ ] Add a _curve_ option on the hull
- [ ] Add a _padding_ option on the hull (see https://observablehq.com/@fil/hull-padding)
- [ ] Add an _alpha_ option on the hull (for alpha shapes)
- [ ] Create a voronoiLabel mark that does occlusion https://observablehq.com/@d3/voronoi-labels
- [ ] ~~Sub-graphs: #941~~
- [x] The Delaunay/Voronoi/Hull marks require x and y, and a such don't accept the result of the dodge transform. Not sure how to approach this generic issue, but a simple work-around is to specify a fake and empty _y_ channel: `Plot.voronoiMesh(penguins, Plot.dodgeY("middle", {x: "body_mass_g", y: []}))` (solved by #931)
- [x] Delaunay and voronoi _can_ work in 1-d (#931)
- [ ] would be nice to have an option to clip the resulting polygons with an arbitrary geometry (#1635 or #1109)

**Comment by mbostock** [comment]
This umbrella issue is over a year old. We should close it and re-open more specific issues as needed.
